services:
  nanogpt:
    command: nvidia-smi dmon
    image: nanogpt
    build:
      context: .
      dockerfile: Dockerfile
    shm_size: 1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    logging:
      options:
        max-size: "100m"
        max-file: "3"
    volumes:
      - .:/workspace/nanogpt
